### PR TITLE
new switches: --dry-run, --no-cleanup, --podman-path

### PR DESCRIPTION
**Pull request by tobwen**
Small refactoring and three new switches:
1. `--dry-run` for debugging (doesn't execute podman),
2. `--no-cleanup` doesn't stop & remove containers on a fresh run,
3. `--podman-path` allows the user to point to podman binary if not in $PATH

### CODE REVIEW

**Comment by muayyad-alsadi** [comment]
there is a lot of changes in the diff, almost every single line is changed! maybe you have reformatted the file! I need sometime to review it

**Comment by tobwen** [comment]
@muayyad-alsadi Yeah sorry, I cleaned up some spaces and indents etc. all in one PR. Shall I rip split it again?

**Comment by muayyad-alsadi** [comment]
no need, I'll review it this weekend.

**Comment by muayyad-alsadi** [comment]
I've undone some of the style changes, like 

```
def adj_hosts(services, cnt, dst = "127.0.0.1"):
```

see [PEP 8](https://www.python.org/dev/peps/pep-0008/#other-recommendations)

> Don't use spaces around the = sign when used to indicate a keyword argument, or when used to indicate a default value for an unannotated function parameter.

**Comment by tobwen** [comment]
I am sorry, I'll use those rules in future.

**Pull request merged**
