### PR TITLE
Support healthcheck associative array

### PR DESCRIPTION
**Pull request by stefanb2**
Map keys to corresponding --healthcheck-XXX option

### CODE REVIEW

**Comment by stefanb2** [comment]
I needed to add `healthcheck` section to my docker-compose.yml because of containers/libpod#3507

**Comment by muayyad-alsadi** [comment]
Thank you very much for this kind contribution. I'll look into it very soon

**Comment by stefanb2** [comment]
Hmm, looks like `['CMD-SHELL', 'echo with whitespace']` does not work correctly, i.e. podman tries to find the executable `echo with whitespace` instead of executing a shell command line.

**Comment by muayyad-alsadi** [comment]
there are two things here

1. build-time (in `Dockerfile`) specification of shell and healthchecks
2. run-time (in `docker-compose.yml`) specification of healthchecks (no shell)

build-time issues should be reported to buildah
run-time issues should be reported to podman

from the compose.yml reference

```
test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
```

which should be interpreted as  

```
test: ["CMD", "/bin/sh", "-c", "curl -f http://localhost || exit 1"]
```

assuming default shell `['/bin/sh', '-c']`

this means that podman should interpret `['CMD-SHELL', 'echo with whitespace']`
as ['CMD', '/bin/sh', '-c',  'echo with whitespace']


https://docs.docker.com/compose/compose-file/#healthcheck
https://docs.docker.com/engine/reference/builder/#healthcheck

**Comment by muayyad-alsadi** [comment]
I've seen the diff, it's not `podman` fault, we should pass it the the arguments in wrong way,

no worries, I'll fixes it ASAP.

**Comment by stefanb2** [comment]
Unfortunately things aren't that easy. It turns out that `--healthcheck-command` really only accepts a string, not a list of strings. Furthermore the string gets split on whitespace, i.e. 
```
--healthcheck-command "stat /etc/passwd || exit 1"
```
ends up in the container configuration as
```json
"Healthcheck": {
    "Test": [
        "stat",
        "/etc/passwd",
        "||",
        "exit",
        "1"
    ],
```

My updated patch tries to approximate as best as possible, but not all valid Docker Compose values will be able to be mapped correctly

**Comment by muayyad-alsadi** [comment]
I've used 

```
from shlex import quote as cmd_quote
```

**Pull request merged**
